#!/bin/bash
#BSUB -J HTS2D
#BSUB -q debug
#BSUB -n 10
#BSUB -W 00:10
#BSUB -e %J-petsc.err
#BSUB -o %J-petsc.out

K=10
N=100

HTS2D_DIR="/work/ese-chenph/github/MAE5032_FinalProject"
cd $HTS2D_DIR

module purge
module load mpi/intel/2018.4

cd build
make HTS2D

rm -rf ../data/*

mpirun -np 10 ./HTS2D generator -fname ../data/test01_ex.hdf5 -n 100 -dl 0.01 -dt 100 -g 100 -rho 5000 -c 1000 -k 1 -f 0 -u0 50
mpirun -np 10 ./HTS2D explicit -fname ../data/test01_ex.hdf5 -tol 1e-7 -ps 1000 -maxItsW 100000 -maxIts 100000 -restart 0> test01_ex.log 2>&1

# mpirun -np $K ./HTS2D generator -fname ../data/test01_im.hdf5 -n $N -dl 0.01 -dt 1 -g 200 -rho 300 -c 1000 -k 10 -f 0 -u0 50
# mpirun -np $K ./HTS2D implicit -fname ../data/test01_im.hdf5 -maxItsW 1000 -maxIts 1000 -restart 0 -log_view > xxxtest01_im.log 2>&1

mv test01_ex.log ../TaiYi_Material/test01_ex.log
#mv test01_im.log ../TaiYi_Material/test01_im.log